version: '3.8'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=ap-northeast-1

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: clinical-trial-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - dynamodb-local
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: clinical-trial-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

volumes:
  dynamodb_data: